# Generated by Django 5.0.3 on 2024-03-23 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Doctor'), (3, 'Client'), (4, 'Sales'), (5, 'Consultant')], default=3)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('dateJoined', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_img', models.ImageField(blank=True, default='/ProfilePic/default.jpg', null=True, upload_to='ProfilePic/')),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SalesTeamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('passwordString', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesDetails', to='Accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('medicalCouncil', models.CharField(max_length=20, null=True)),
                ('councilRegNo', models.CharField(max_length=200, null=True)),
                ('hospitals', models.CharField(max_length=300, null=True)),
                ('interests', models.CharField(max_length=200, null=True)),
                ('placeOfWork', models.CharField(max_length=200, null=True)),
                ('onlineConsultation', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('languages', models.CharField(default='', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('referalId', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docDetails', to='Accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth_parent', models.DateField(blank=True, null=True)),
                ('babydob', models.DateField(null=True)),
                ('profile_img', models.ImageField(blank=True, default='/ProfilePic/default.jpg', null=True, upload_to='ProfilePic/')),
                ('babyGender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('doctor_referal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.doctordetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('passwordString', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultantDetails', to='Accounts.user')),
            ],
        ),
    ]
