# Generated by Django 5.0.3 on 2024-03-23 11:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('schedule', models.DateTimeField(default=datetime.datetime.now)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rescheduled_by_doctor', models.BooleanField(default=False)),
                ('rescheduled_by_client', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(null=True)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='Accounts.customerdetails')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.doctordetails')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.appointments')),
            ],
        ),
    ]
